credentials:
  usernames:
    dkuzin:
      email: dmitrkuzin@gmail.com
      name: Dmitriy Kuzin
      password: '$2b$12$rIFwZOEW2nvjvLZ6TX.WLeTLXyyPtGWfSlMD5vexY2c7m83J6f.M6'
cookie:
  expiry_days: 30
  key: random_signature_key
  name: random_cookie_name
preauthorized:
  emails:
    - melsby@gmail.com